/* Persistentes Außentest-Protokoll und verständliche Laufzeitdiagnose. */
const RAVEN_FIELD_KEY="ravenFieldTestV1",RAVEN_DIAGNOSTIC_KEY="ravenDiagnosticsV1";
const RAVEN_FIELD_STEPS=["Spieler-App vom Habitat starten","genauen GPS-Standort erhalten","Fog beim Gehen sichtbar öffnen","Erkundungspunkt im Radius freirubbeln","Aktivitätspunkt und Item erhalten","Tour beenden und Reisebericht prüfen"];
function ravenSafeArray(key){try{const value=JSON.parse(localStorage.getItem(key)||"[]");return Array.isArray(value)?value:[];}catch{return[];}}
function ravenSafeObject(key,fallback={}){try{return{...fallback,...JSON.parse(localStorage.getItem(key)||"null")};}catch{return{...fallback};}}
function addRavenDiagnostic(kind,message,detail=""){const entries=ravenSafeArray(RAVEN_DIAGNOSTIC_KEY);entries.push({time:Date.now(),kind:String(kind),message:String(message).slice(0,180),detail:String(detail).slice(0,240)});localStorage.setItem(RAVEN_DIAGNOSTIC_KEY,JSON.stringify(entries.slice(-100)));renderRavenFieldDiagnostics();}
function loadRavenFieldTest(){return ravenSafeObject(RAVEN_FIELD_KEY,{startedAt:Date.now(),checks:[],notes:""});}
function renderRavenFieldTest(){const state=loadRavenFieldTest(),box=document.getElementById("fieldChecklist"),notes=document.getElementById("fieldTestNotes"),progress=document.getElementById("fieldTestProgress");if(!box)return;box.innerHTML=RAVEN_FIELD_STEPS.map((label,index)=>`<label><input type="checkbox" data-field-step="${index}" ${state.checks.includes(index)?"checked":""}><span>${label}</span></label>`).join("");if(notes&&document.activeElement!==notes)notes.value=state.notes||"";if(progress)progress.textContent=`${state.checks.length}/${RAVEN_FIELD_STEPS.length}`;renderRavenFieldDiagnostics();}
function saveRavenFieldTest(){const previous=loadRavenFieldTest(),checks=[...document.querySelectorAll("[data-field-step]:checked")].map(input=>Number(input.dataset.fieldStep)),notes=document.getElementById("fieldTestNotes")?.value||"",state={startedAt:previous.startedAt||Date.now(),updatedAt:Date.now(),checks,notes};localStorage.setItem(RAVEN_FIELD_KEY,JSON.stringify(state));renderRavenFieldTest();addRavenDiagnostic("test","Außentest-Zwischenstand gespeichert",`${checks.length}/${RAVEN_FIELD_STEPS.length}`);}
function ravenDiagnosticSummary(){const entries=ravenSafeArray(RAVEN_DIAGNOSTIC_KEY),errors=entries.filter(entry=>entry.kind==="error");return{entries,errors};}
function renderRavenFieldDiagnostics(){const box=document.getElementById("fieldDiagnostics");if(!box)return;const{entries,errors}=ravenDiagnosticSummary(),last=entries.at(-1);box.innerHTML=`<b>${errors.length?"⚠":"✓"} ${errors.length} technische Fehler</b><span>${last?`${new Date(last.time).toLocaleTimeString("de-DE")} · ${escapeHTML(last.message)}`:"Noch keine Auffälligkeiten protokolliert."}</span>`;}
function ravenFieldReportText(){const field=loadRavenFieldTest(),diagnostics=ravenDiagnosticSummary(),life=ravenSafeObject("ravenLife",{}),profile=ravenSafeObject("ravenProfile",{name:"Raven"}),reports=ravenSafeArray("ravenTourReportsV1"),events=ravenSafeArray("ravenTestEvents");return["RAVEN AUSSENTEST-PROTOKOLL",new Date().toLocaleString("de-DE"),`Gerät: ${navigator.userAgent}`,"",`Raven: ${profile.name||"Raven"} · Hunger ${Math.round(life.hunger||0)} · Energie ${Math.round(life.energy||0)} · Stimmung ${Math.round(life.mood||0)}`,"",...RAVEN_FIELD_STEPS.map((step,index)=>`${field.checks.includes(index)?"[x]":"[ ]"} ${step}`),"","BEOBACHTUNGEN",field.notes||"Keine Notizen.","","LETZTE REISEN",...(reports.slice(-10).map(report=>`${new Date(report.endedAt).toLocaleString("de-DE")} · ${(report.distance/1000).toFixed(2)} km · ${report.explored} Erkundung · ${report.activities} Aktivitäten · +${report.items} Items · +${report.xp} XP`)||[]),"","TECHNISCHE DIAGNOSE",...(diagnostics.entries.slice(-40).map(entry=>`${new Date(entry.time).toLocaleTimeString("de-DE")} · ${entry.kind.toUpperCase()} · ${entry.message}${entry.detail?" · "+entry.detail:""}`)),"","SPIELEREIGNISSE",...events.slice(-40).map(entry=>`${new Date(entry.time).toLocaleTimeString("de-DE")} · ${entry.type}${entry.detail?" · "+entry.detail:""}`)].join("\n");}
function downloadRavenFieldReport(){saveRavenFieldTest();const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([ravenFieldReportText()],{type:"text/plain;charset=utf-8"}));link.download=`raven-aussentest-${new Date().toISOString().slice(0,10)}.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}
window.addEventListener("error",event=>addRavenDiagnostic("error",event.message||"Unbekannter JavaScript-Fehler",`${event.filename||""}:${event.lineno||0}`));
window.addEventListener("unhandledrejection",event=>addRavenDiagnostic("error","Nicht behandelter App-Fehler",event.reason?.message||String(event.reason||"")));
window.addEventListener("online",()=>addRavenDiagnostic("info","Internetverbindung wiederhergestellt"));window.addEventListener("offline",()=>addRavenDiagnostic("warning","Internetverbindung unterbrochen"));
window.reportRavenGpsProblem=(message,detail="")=>addRavenDiagnostic("error",message,detail);
window.addEventListener("DOMContentLoaded",()=>{renderRavenFieldTest();document.getElementById("fieldChecklist")?.addEventListener("change",saveRavenFieldTest);});

