/* Spielerfluss: Habitat -> Erkundung -> Reisebericht -> Habitat. */
const RAVEN_TOUR_START_KEY="ravenTourStartV1",RAVEN_TOUR_REPORT_KEY="ravenTourReportV1";
let ravenHubView="habitat";
function ravenCountItems(items={}){return Object.values(items).reduce((sum,value)=>sum+(Number(value)||0),0);}
function ravenTourSnapshot(){const activityVisits=readRavenHubJSON("ravenActivityVisited"),place=document.getElementById("locationName")?.textContent||"";return{startedAt:Date.now(),distance:Number(totalDistance)||0,xp:Number(xp)||0,explored:Array.isArray(exploredPoints)?exploredPoints.length:0,activities:Array.isArray(activityVisits)?activityVisits.length:0,items:ravenCountItems(typeof ravenItems!=="undefined"?ravenItems:{}),place:String(place)};}
function saveRavenTourStart(){const snapshot=ravenTourSnapshot();localStorage.setItem(RAVEN_TOUR_START_KEY,JSON.stringify(snapshot));return snapshot;}
function readRavenHubJSON(key){try{return JSON.parse(localStorage.getItem(key)||"null");}catch{return null;}}
function showRavenHubView(view){ravenHubView=view==="exploration"?"exploration":"habitat";document.body.dataset.hubView=ravenHubView;document.getElementById("habitatTab")?.classList.toggle("active",ravenHubView==="habitat");document.getElementById("explorationTab")?.classList.toggle("active",ravenHubView==="exploration");if(ravenHubView==="exploration")setTimeout(()=>{if(typeof map!=="undefined")map.invalidateSize();},80);window.scrollTo({top:0,behavior:"smooth"});}
function beginRavenJourney(){const readiness=typeof canRavenStartExploration==="function"?canRavenStartExploration():{ok:true};if(!readiness.ok){setRavenLifeMessage(readiness.message);document.getElementById("journeyReadiness").textContent="NOCH NICHT";return;}saveRavenTourStart();showRavenHubView("exploration");if(!tracking)startExploration();}
function buildRavenTourReport(distanceBeforeStop){const start=readRavenHubJSON(RAVEN_TOUR_START_KEY)||ravenTourSnapshot(),end=ravenTourSnapshot(),report={endedAt:Date.now(),minutes:Math.max(0,Math.round((Date.now()-(start.startedAt||Date.now()))/60000)),distance:Math.max(0,Number(distanceBeforeStop)||0),xp:Math.max(0,end.xp-(start.xp||0)),explored:Math.max(0,end.explored-(start.explored||0)),activities:Math.max(0,end.activities-(start.activities||0)),items:Math.max(0,end.items-(start.items||0)),place:end.place||start.place||"Unbekannt"};localStorage.setItem(RAVEN_TOUR_REPORT_KEY,JSON.stringify(report));localStorage.removeItem(RAVEN_TOUR_START_KEY);return report;}
function finishRavenJourney(){const distanceBeforeStop=Number(sessionDistance)||0;if(tracking)stopExploration();const report=buildRavenTourReport(distanceBeforeStop);renderRavenJourneySummary(report);showRavenHubView("habitat");showRavenReaction("happy",report.explored||report.activities?"Was für ein Abenteuer! ✨":"Willkommen zurück! 🏠",2200);}
function renderRavenJourneySummary(report=readRavenHubJSON(RAVEN_TOUR_REPORT_KEY)){const box=document.getElementById("journeySummary");if(!box)return;if(!report){box.textContent="Noch keine abgeschlossene Tour in dieser Version.";return;}box.innerHTML=`<strong>Letzte Reise${report.place&&report.place!=="Unbekannt"?` · ${escapeHTML(report.place)}`:""}</strong><span>🥾 ${(Number(report.distance)/1000).toFixed(2)} km</span><span>🟣 ${report.explored} neu</span><span>🟠 ${report.activities} gesammelt</span><span>🎒 +${report.items} Items</span><span>✨ +${report.xp} XP</span>`;}
function updateRavenJourneyReadiness(){const badge=document.getElementById("journeyReadiness"),readiness=typeof canRavenStartExploration==="function"?canRavenStartExploration():{ok:true};if(badge){badge.textContent=readiness.ok?"BEREIT":"VERSORGEN";badge.classList.toggle("blocked",!readiness.ok);}}
window.addEventListener("DOMContentLoaded",()=>{showRavenHubView("habitat");renderRavenJourneySummary();updateRavenJourneyReadiness();setInterval(updateRavenJourneyReadiness,30000);});

