const fs=require("node:fs");
const assert=require("node:assert/strict");
const map=fs.readFileSync("js/map.js","utf8");
const gps=fs.readFileSync("js/gps.js","utf8");
const travel=fs.readFileSync("js/travelbook.js","utf8");
const world=fs.readFileSync("js/germany-world.js","utf8");
const storage=fs.readFileSync("js/storage.js","utf8");
const shared=fs.readFileSync("js/shared-pois.js","utf8");
assert.match(gps,/navigator\.geolocation\.watchPosition/,"Browser-GPS fehlt");
assert.match(gps,/enableHighAccuracy:true/,"Präzises GPS muss angefordert werden");
assert.match(map,/GERMANY_BOUNDS/);
assert.doesNotMatch(travel,/allowedOrtschaften=new Set\(\["Fürstenberg"\]\)/,"Fürstenberg-Sperre ist noch aktiv");
assert.match(travel,/address\.country_code/,"Deutschlandgrenze wird nicht geprüft");
assert.match(travel,/currentRavenDistrict=name\|\|null/,"Erkannter Ort wird nicht aktiviert");
assert.match(travel,/loadRavenPlacePoints/,"GPS-Erkennung startet keine Orts-POIs");
assert.doesNotMatch(storage,/ravenAllowedDistricts/,"Gespeicherte Deutschlandorte würden wieder gelöscht");
assert.match(world,/hamlet:\{radius:1300,exploration:2,activity:3/);
assert.match(world,/city:\{radius:6500,exploration:10,activity:14/);
assert.match(world,/out center tags 180/,"POI-Abfrage besitzt keine harte Ergebnisgrenze");
assert.match(world,/createRavenFallbackPoints/,"Punkte fehlen, solange offene Ortsdaten laden");
assert.match(world,/ravenPointInGeometry/,"POIs werden nicht gegen die Ortsgrenze geprüft");
assert.match(world,/ravenBoundaryClearanceMeters/,"POIs besitzen keinen Sicherheitsabstand zur Ortsgrenze");
assert.match(world,/ravenPointSafelyInsidePlace\(point,place,80\)/,"Echte Ortsdaten werden nicht vom Grenzrand ferngehalten");
assert.match(shared,/maxMeters:1600/,"Fürstenbergs automatische Punkte sind nicht auf den Dorfkern begrenzt");
assert.match(shared,/isOwnStudioPoint\(point\)\|\|distanceFromFuerstenbergCore\(point\)<=fuerstenbergCore\.maxMeters/,"Fürstenberg-Import umgeht die Dorfkernprüfung");
assert.match(world,/registerRavenPlaceBoundary/,"Deutsche Ortsgrenzen werden nicht gespeichert");
assert.match(world,/ravenGermanyBoundaryLayer/,"Mehrere entdeckte Gebiete können nicht gemeinsam angezeigt werden");
assert.match(travel,/registerRavenPlaceBoundary/,"GPS-Ortsgrenze wird nicht an die Deutschlandkarte übergeben");
console.log("✓ Deutschland-GPS-Test bestanden: präziser Standort, freie deutsche Orte und begrenzte POI-Nachladung");
