const PROFILES=[
  ["Ayla","Sanft",1.4,.8,.6,.7,30,90],["Bo","Ausdauer",1.7,1,.8,.8,35,75],["Cleo","Aktiv",2,1.2,1,1,38,60],["Dax","Hungrig",2.6,1.1,.9,1,42,60],["Edda","Müde",1.8,1.8,1.1,.9,35,75],["Fynn","Vielspieler",2.2,1.5,1.2,1.1,40,45],["Gina","Sparsam",1.6,1,.7,.75,25,120],["Hugo","Aktuell",2.2,1.3,.8,1,35,60],["Ivy","Streng",3.2,2,1.4,1.3,45,45],["Kiro","Locker",1.2,.7,.5,.6,22,120]
].map((p,i)=>({id:i,name:p[0],label:p[1],hungerHour:p[2],energyHour:p[3],moodHour:p[4],moveCost:p[5],feedAt:p[6],cooldown:p[7]}));
const FALLBACK_POINTS=[
 {name:"Rathaus",type:"exploration",lat:51.5157,lon:8.7398},{name:"Handwerkerhäuser",type:"exploration",lat:51.51438,lon:8.73964},{name:"Spielplatz",type:"activity",lat:51.5152,lon:8.7432},{name:"Brunnen",type:"activity",lat:51.51393,lon:8.73676},{name:"Sportplatz",type:"activity",lat:51.5192,lon:8.7445},{name:"Park",type:"activity",lat:51.5118,lon:8.7374}
];
let points=FALLBACK_POINTS,bots=[],minute=0,timer=null,events=[],map,poiLayer,botLayer,routes=[];
function rand(bot,salt=0){let x=Math.sin((bot.id+1)*999+minute*17+salt*71)*43758.5453;return x-Math.floor(x);}
function makeBot(profile){return {...profile,hunger:80,energy:80,mood:75,items:2,xp:0,distance:0,feeds:0,plays:0,jumpers:0,visits:0,critical:0,sleep:0,moodSum:0,samples:0,pointIndex:profile.id%points.length,lat:51.5157,lon:8.741,trail:[],lastActivity:-9999};}
async function loadPoints(){try{const data=await (await fetch("../data/bad-wuennenberg-pois.json",{cache:"no-store"})).json(),source=data.points||data.candidates||[];const loaded=source.filter(p=>p.status!=="rejected"&&(p.district||"")==="Fürstenberg").slice(0,18).map(p=>({name:p.name||"Punkt",type:p.category==="activity"?"activity":"exploration",lat:+p.lat,lon:+p.lon})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));if(loaded.length)points=loaded;}catch{}resetSimulation();drawPoints();restoreSavedReport();}
function initMap(){map=L.map("simMap",{zoomControl:true,minZoom:13}).setView([51.5157,8.741],15);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap",keepBuffer:1}).addTo(map);poiLayer=L.layerGroup().addTo(map);botLayer=L.layerGroup().addTo(map);}
function drawPoints(){poiLayer.clearLayers();points.forEach(p=>L.marker([p.lat,p.lon],{icon:L.divIcon({className:"",html:`<div class="sim-poi ${p.type}">${p.type==="activity"?"◆":"?"}</div>`,iconSize:[20,20],iconAnchor:[10,10]})}).bindTooltip(p.name).addTo(poiLayer));}
function resetSimulation(){clearInterval(timer);timer=null;minute=0;events=[];routes.forEach(r=>map?.removeLayer(r));routes=[];botLayer?.clearLayers();bots=PROFILES.map(makeBot);bots.forEach((b,i)=>{b.marker=L.marker([b.lat,b.lon],{icon:L.divIcon({className:"",html:`<div class="sim-bot">${i+1}</div>`,iconSize:[24,24],iconAnchor:[12,12]})}).bindTooltip(`${b.name} · ${b.label}`).addTo(botLayer);});render();}
function log(bot,text){events.push(`${timeText()} · ${bot.name}: ${text}`);events=events.slice(-600);}
function timeText(){return `${String(Math.floor(minute/60)).padStart(2,"0")}:${String(minute%60).padStart(2,"0")}`;}
function visitPoint(bot){const p=points[bot.pointIndex%points.length];bot.pointIndex++;bot.visits++;bot.xp+=p.type==="activity"?10:25;if(p.type==="activity"){bot.items++;bot.lastActivity=minute;log(bot,`${p.name} besucht, Item +1`);}else{bot.mood=Math.min(100,bot.mood+3);log(bot,`${p.name} erkundet`);}bot.lat=p.lat;bot.lon=p.lon;bot.marker?.setLatLng([bot.lat,bot.lon]);bot.trail.push([bot.lat,bot.lon]);if(bot.trail.length>1)routes.push(L.polyline(bot.trail.slice(-2),{color:`hsl(${bot.id*36} 75% 55%)`,weight:2,opacity:.45}).addTo(map));}
function tickBot(bot,step){const hour=(minute/60)%24,sleeping=hour>=23||hour<7;bot.hunger=Math.max(0,bot.hunger-bot.hungerHour*step/60);bot.mood=Math.max(0,bot.mood-bot.moodHour*step/60);if(sleeping){bot.energy=Math.min(100,bot.energy+7*step/60);bot.sleep+=step;}else bot.energy=Math.max(0,bot.energy-bot.energyHour*step/60);
  const walking=!sleeping&&((hour>=8&&hour<10)||(hour>=15&&hour<18));if(walking){const km=(3.6+bot.id*.12)*step/60;bot.distance+=km;bot.hunger=Math.max(0,bot.hunger-km*bot.moveCost);bot.energy=Math.max(0,bot.energy-km*bot.moveCost*.6);if(minute-bot.lastActivity>=bot.cooldown&&rand(bot)<.42)visitPoint(bot);}
  if(!sleeping&&bot.hunger<bot.feedAt&&bot.items>0){bot.items--;bot.hunger=Math.min(100,bot.hunger+24);bot.mood=Math.min(100,bot.mood+4);bot.feeds++;log(bot,"gefüttert");}
  if(!sleeping&&bot.energy>18&&minute%120<step&&rand(bot,2)<.65){bot.energy=Math.max(0,bot.energy-8);bot.hunger=Math.max(0,bot.hunger-6);bot.mood=Math.min(100,bot.mood+18);bot.plays++;log(bot,"gespielt");}
  if(!sleeping&&bot.energy>20&&minute%240<step&&rand(bot,4)<.42){bot.energy-=6;bot.hunger=Math.max(0,bot.hunger-3);bot.mood=Math.min(100,bot.mood+5);bot.jumpers++;log(bot,"Raven Jumper gespielt");}
  const visibleMood=Math.min(bot.mood,(bot.hunger+bot.energy)/2+15);if(bot.hunger<15||bot.energy<15||visibleMood<20)bot.critical+=step;bot.moodSum+=visibleMood;bot.samples++;}
function advance(){let remaining=Math.min(+document.getElementById("speed").value,1440-minute);while(remaining>0){const step=Math.min(6,remaining);for(const bot of bots)tickBot(bot,step);minute+=step;remaining-=step;}render();if(minute>=1440)finish();}
function start(){if(minute>=1440)resetSimulation();if(timer)return;timer=setInterval(advance,1000);document.getElementById("summary").textContent="Simulation läuft. Die Seite kann sichtbar geöffnet bleiben; der Bericht wird am Ende gespeichert.";}
function pause(){clearInterval(timer);timer=null;document.getElementById("summary").textContent=`Pausiert bei ${timeText()}. Der Zwischenstand bleibt erhalten.`;}
function score(b){return b.critical*3+Math.abs(b.feeds-3)*20+(100-(b.moodSum/Math.max(1,b.samples)))*2+Math.max(0,3-b.visits)*12;}
function finish(){pause();const ranked=[...bots].sort((a,b)=>score(a)-score(b)),best=ranked[0];const report={createdAt:new Date().toISOString(),minutes:minute,bots:bots.map(b=>({...b,marker:undefined,trail:b.trail.slice(-30),averageMood:Math.round(b.moodSum/Math.max(1,b.samples)),balanceScore:Math.round(score(b))})),events};localStorage.setItem("ravenDaySimulationReport",JSON.stringify(report));document.getElementById("summary").textContent=`24 Stunden abgeschlossen. ${best.name} (${best.label}) liefert aktuell die ausgeglichensten Werte.`;document.getElementById("recommendation").innerHTML=`<b>Erste Empfehlung: ${best.name} · ${best.label}</b><br>Hunger ${best.hungerHour}/h · Energie ${best.energyHour}/h · Bewegung ${best.moveCost}/km · Füttern unter ${best.feedAt} · Aktivitäts-Cooldown ${best.cooldown} Minuten.`;render();}
function render(){document.getElementById("clock").textContent=`Tag 1 · ${timeText()}`;const ranked=minute>=1440?[...bots].sort((a,b)=>score(a)-score(b)):[],best=ranked[0];document.getElementById("botGrid").innerHTML=bots.map(b=>{const vm=Math.max(0,Math.round(Math.min(b.mood,(b.hunger+b.energy)/2+15)));return `<article class="bot ${best===b?"best":""}"><h3><span>${b.id+1}. ${b.name} · ${b.label}</span><small>${b.hungerHour}/${b.energyHour}/${b.moveCost}</small></h3><div class="stats"><b>🍖 ${Math.round(b.hunger)}</b><b>⚡ ${Math.round(b.energy)}</b><b>💜 ${vm}</b><b>🎒 ${b.items}</b></div><div class="bars"><div class="bar"><span>Hunger</span><i style="width:${b.hunger}%"></i><em>${Math.round(b.hunger)}</em></div><div class="bar"><span>Energie</span><i style="width:${b.energy}%"></i><em>${Math.round(b.energy)}</em></div></div><footer>${b.distance.toFixed(1)} km · ${b.visits} Punkte · ${b.feeds}× gefüttert · ${b.plays}× gespielt · ${b.jumpers}× Jumper · ${b.critical} kritische Min.</footer></article>`;}).join("");document.getElementById("eventLog").innerHTML=events.length?events.slice(-120).reverse().join("<br>"):"Noch keine Ereignisse.";}
function download(){const raw=localStorage.getItem("ravenDaySimulationReport");if(!raw)return alert("Erst eine Simulation abschließen.");const data=JSON.parse(raw),lines=["RAVEN 24-STUNDEN-SIMULATION",data.createdAt,""];data.bots.sort((a,b)=>a.balanceScore-b.balanceScore).forEach(b=>lines.push(`${b.name} / ${b.label}: Score ${b.balanceScore}, Hunger ${Math.round(b.hunger)}, Energie ${Math.round(b.energy)}, Stimmung Ø ${b.averageMood}, ${b.distance.toFixed(1)} km, ${b.visits} Besuche, ${b.feeds} Fütterungen, ${b.critical} kritische Minuten`));lines.push("","EREIGNISSE",...data.events);const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([lines.join("\n")],{type:"text/plain;charset=utf-8"}));a.download="raven-24h-simulation.txt";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function restoreSavedReport(){try{const data=JSON.parse(localStorage.getItem("ravenDaySimulationReport")||"null");if(!data?.bots?.length)return;const best=[...data.bots].sort((a,b)=>a.balanceScore-b.balanceScore)[0];document.getElementById("summary").textContent=`Gespeicherter 24-Stunden-Bericht vom ${new Date(data.createdAt).toLocaleString("de-DE")}. Neuer Lauf überschreibt ihn erst nach Abschluss.`;document.getElementById("recommendation").innerHTML=`<b>Gespeichertes Ergebnis: ${best.name} · ${best.label}</b><br>Hunger ${best.hungerHour}/h · Energie ${best.energyHour}/h · Bewegung ${best.moveCost}/km · Cooldown ${best.cooldown} Minuten · Balance-Score ${best.balanceScore}.`;document.getElementById("eventLog").innerHTML=(data.events||[]).slice(-120).reverse().join("<br>")||"Der gespeicherte Bericht enthält keine Ereignisse.";}catch{}}
document.getElementById("startButton").onclick=start;document.getElementById("pauseButton").onclick=pause;document.getElementById("resetButton").onclick=resetSimulation;document.getElementById("downloadButton").onclick=download;initMap();loadPoints();

