const PROFILES=[["Ayla","Sanft",1.4,.8,.6,.7,30,90],["Bo","Ausdauer",1.7,1,.8,.8,35,75],["Cleo","Aktiv",2,1.2,1,1,38,60],["Dax","Hungrig",2.6,1.1,1,1,42,60],["Edda","Müde",1.8,1.8,.9,.9,35,75],["Fynn","Vielspieler",2.2,1.5,1.1,1.1,40,45],["Gina","Sparsam",1.6,1,.7,.75,25,120],["Hugo","Aktuell",2.2,1.3,1,1,35,60],["Ivy","Streng",3.2,2,1.3,1.3,45,45],["Kiro","Locker",1.2,.7,.6,.6,22,120]].map((p,id)=>({id,name:p[0],label:p[1],hungerHour:p[2],energyHour:p[3],moodHour:p[4],moveCost:p[5],feedAt:p[6],cooldown:p[7]}));
const ROUTER="https://routing.openstreetmap.de/routed-foot/route/v1/driving",STREET_LOOPS=[[[51.5157,8.741],[51.5191,8.745],[51.5164,8.750],[51.5128,8.746],[51.5119,8.738],[51.5157,8.741]],[[51.5157,8.741],[51.5184,8.736],[51.5202,8.741],[51.5172,8.748],[51.5135,8.744],[51.5157,8.741]],[[51.5157,8.741],[51.5138,8.735],[51.5107,8.738],[51.5126,8.747],[51.5170,8.746],[51.5157,8.741]],[[51.5157,8.741],[51.5160,8.734],[51.5203,8.736],[51.5194,8.746],[51.5145,8.749],[51.5157,8.741]]];
let points=[],boundary=null,bots=[],minute=0,timer=null,events=[],map,poiLayer,botLayer,boundaryLayer,routeLayers=[],routes=[],ready=false;
function pointInRing(lon,lat,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [xi,yi]=ring[i],[xj,yj]=ring[j],hit=(yi>lat)!==(yj>lat)&&lon<(xj-xi)*(lat-yi)/(yj-yi)+xi;if(hit)inside=!inside;}return inside;}
function insideBoundary(p){if(!boundary)return true;const polygons=boundary.type==="Polygon"?[boundary.coordinates]:boundary.coordinates||[];return polygons.some(poly=>pointInRing(p.lon,p.lat,poly[0])&&!poly.slice(1).some(hole=>pointInRing(p.lon,p.lat,hole)));}
function normalizePoint(p){const kind=p.category||p.type;return{id:p.id||`${p.lat}-${p.lon}`,name:p.name||"Punkt",type:kind==="activity"?"activity":"exploration",lat:+p.lat,lon:+p.lon,radius:+(p.radius||p.discoveryRadius)||(kind==="activity"?80:60),status:p.status||"pending"};}
async function loadSharedWorld(){const boundaryData=await(await fetch("../data/fuerstenberg-boundary.json?v=1",{cache:"no-store"})).json();boundary=boundaryData.geojson;let source,usingStudio=false;try{const live=JSON.parse(localStorage.getItem("ravenSharedPoisLive")||"null");if(Array.isArray(live?.points)){source=live.points;usingStudio=true;}}catch{}if(!source){const data=await(await fetch("../data/bad-wuennenberg-pois.json?v=28sync1",{cache:"no-store"})).json();source=data.points||data.candidates||[];}const curated=new Set(["osm-node-12779747489","osm-way-248558859","osm-way-933203680","osm-way-711609936","osm-way-257138078","osm-way-815079785","osm-way-32636625","osm-way-249788369"]);points=source.filter(p=>(p.district||"Fürstenberg")==="Fürstenberg"&&(usingStudio||curated.has(p.id))).map(normalizePoint).filter(p=>p.status!=="rejected"&&Number.isFinite(p.lat)&&Number.isFinite(p.lon)&&insideBoundary(p));drawWorld();await prepareStreetRoutes();resetSimulation();ready=true;document.getElementById("summary").textContent=`Bereit: ${points.length} gemeinsame Fürstenberg-Punkte · ${routes.length} Straßenrouten · Quelle: ${usingStudio?"Studio":"Spiel-Grunddaten"}.`;restoreSavedReport();}
function initMap(){const gameBounds=L.latLngBounds([51.447216,8.709994],[51.555537,8.837855]);map=L.map("simMap",{zoomControl:true,minZoom:12,maxBounds:gameBounds,maxBoundsViscosity:1}).setView([51.5157,8.741],15);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,noWrap:true,bounds:gameBounds.pad(.15),attribution:"© OpenStreetMap",keepBuffer:2}).addTo(map);poiLayer=L.layerGroup().addTo(map);botLayer=L.layerGroup().addTo(map);}
function drawWorld(){poiLayer.clearLayers();if(boundaryLayer)map.removeLayer(boundaryLayer);boundaryLayer=L.geoJSON(boundary,{style:{color:"#facc15",weight:3,fillOpacity:.025}}).addTo(map);map.setView([51.5157,8.741],15);points.forEach(p=>L.marker([p.lat,p.lon],{icon:L.divIcon({className:"",html:`<div class="sim-poi ${p.type}">${p.type==="activity"?"◆":"?"}</div>`,iconSize:[20,20],iconAnchor:[10,10]})}).bindTooltip(`${p.name} · ${p.radius} m`).addTo(poiLayer));}
async function routeLoop(anchors){const coordinates=anchors.map(([lat,lon])=>`${lon},${lat}`).join(";");try{const response=await fetch(`${ROUTER}/${coordinates}?overview=full&geometries=geojson&steps=false`),data=await response.json(),coords=data.routes?.[0]?.geometry?.coordinates;if(!response.ok||!coords?.length)throw Error();return coords.map(([lon,lat])=>[lat,lon]);}catch{events.push("System: Straßenrouter nicht verfügbar – Kontrollpunkte als Notroute.");return anchors;}}
async function prepareStreetRoutes(){routes=await Promise.all(STREET_LOOPS.map(routeLoop));routeLayers.forEach(layer=>map.removeLayer(layer));routeLayers=routes.map((route,i)=>L.polyline(route,{color:`hsl(${i*80+190} 75% 55%)`,weight:3,opacity:.35}).addTo(map));}
function distance(a,b){const R=6371000,dLat=(b[0]-a[0])*Math.PI/180,dLon=(b[1]-a[1])*Math.PI/180,s=Math.sin(dLat/2)**2+Math.cos(a[0]*Math.PI/180)*Math.cos(b[0]*Math.PI/180)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(s));}
function routeLength(route){let total=0;for(let i=1;i<route.length;i++)total+=distance(route[i-1],route[i]);return total;}
function routePosition(route,meters){const total=routeLength(route);let left=((meters%total)+total)%total;for(let i=1;i<route.length;i++){const len=distance(route[i-1],route[i]);if(left<=len){const r=len?left/len:0;return[route[i-1][0]+(route[i][0]-route[i-1][0])*r,route[i-1][1]+(route[i][1]-route[i-1][1])*r];}left-=len;}return route[0];}
function makeBot(profile){const route=routes[profile.id%routes.length]||STREET_LOOPS[0];return{...profile,route,hunger:80,energy:80,mood:75,items:2,xp:0,distance:0,routeMeters:profile.id*45,feeds:0,plays:0,jumpers:0,visits:0,critical:0,sleep:0,moodSum:0,samples:0,found:{},activityTimes:{},lat:route[0][0],lon:route[0][1]};}
function rand(bot,salt=0){let x=Math.sin((bot.id+1)*999+minute*17+salt*71)*43758.5453;return x-Math.floor(x);}
function resetSimulation(){clearInterval(timer);timer=null;minute=0;events=[];botLayer.clearLayers();bots=PROFILES.map(makeBot);bots.forEach((b,i)=>{b.marker=L.marker([b.lat,b.lon],{icon:L.divIcon({className:"",html:`<div class="sim-bot">${i+1}</div>`,iconSize:[24,24],iconAnchor:[12,12]})}).bindTooltip(`${b.name} · ${b.label}`).addTo(botLayer);});render();}
function log(bot,text){events.push(`${timeText()} · ${bot.name}: ${text}`);events=events.slice(-800);}function timeText(){return`${String(Math.floor(minute/60)).padStart(2,"0")}:${String(minute%60).padStart(2,"0")}`;}
function discoverAlongStreet(bot){for(const p of points){const meters=distance([bot.lat,bot.lon],[p.lat,p.lon]),last=bot.activityTimes[p.id]??-99999;if(meters>p.radius)continue;if(p.type==="exploration"){if(bot.found[p.id])continue;bot.found[p.id]=true;bot.visits++;bot.xp+=25;bot.mood=Math.min(100,bot.mood+3);log(bot,`${p.name} zufällig am Weg entdeckt (${Math.round(meters)} m)`);}else if(minute-last>=bot.cooldown){bot.activityTimes[p.id]=minute;bot.visits++;bot.xp+=10;bot.items++;log(bot,`${p.name} im Vorbeigehen gesammelt (${Math.round(meters)} m)`);}}}
function tickBot(bot,step){const hour=(minute/60)%24,sleeping=hour>=23||hour<7;bot.hunger=Math.max(0,bot.hunger-bot.hungerHour*step/60);bot.mood=Math.max(0,bot.mood-bot.moodHour*step/60);if(sleeping){bot.energy=Math.min(100,bot.energy+7*step/60);bot.sleep+=step;}else bot.energy=Math.max(0,bot.energy-bot.energyHour*step/60);const walking=!sleeping&&((hour>=8&&hour<10)||(hour>=15&&hour<18));if(walking){const km=(3.6+bot.id*.12)*step/60;bot.distance+=km;bot.routeMeters+=km*1000;bot.hunger=Math.max(0,bot.hunger-km*bot.moveCost);bot.energy=Math.max(0,bot.energy-km*bot.moveCost*.6);const pos=routePosition(bot.route,bot.routeMeters);bot.lat=pos[0];bot.lon=pos[1];bot.marker.setLatLng(pos);discoverAlongStreet(bot);}if(!sleeping&&bot.hunger<bot.feedAt&&bot.items>0){bot.items--;bot.hunger=Math.min(100,bot.hunger+24);bot.mood=Math.min(100,bot.mood+4);bot.feeds++;log(bot,"gefüttert");}if(!sleeping&&bot.energy>18&&minute%120<step&&rand(bot,2)<.65){bot.energy=Math.max(0,bot.energy-8);bot.hunger=Math.max(0,bot.hunger-6);bot.mood=Math.min(100,bot.mood+18);bot.plays++;log(bot,"gespielt");}if(!sleeping&&bot.energy>20&&minute%240<step&&rand(bot,4)<.42){bot.energy-=6;bot.hunger=Math.max(0,bot.hunger-3);bot.mood=Math.min(100,bot.mood+5);bot.jumpers++;log(bot,"Raven Jumper gespielt");}const visible=Math.min(bot.mood,(bot.hunger+bot.energy)/2+15);if(bot.hunger<15||bot.energy<15||visible<20)bot.critical+=step;bot.moodSum+=visible;bot.samples++;}
function advance(){let remaining=Math.min(+document.getElementById("speed").value,1440-minute);while(remaining>0){const step=Math.min(3,remaining);bots.forEach(bot=>tickBot(bot,step));minute+=step;remaining-=step;}render();if(minute>=1440)finish();}
function start(){if(!ready)return;if(minute>=1440)resetSimulation();if(timer)return;timer=setInterval(advance,1000);document.getElementById("summary").textContent="Simulation läuft: Straßen werden abgelaufen; Punkte zählen nur bei echter Radiusberührung.";}function pause(){clearInterval(timer);timer=null;document.getElementById("summary").textContent=`Pausiert bei ${timeText()}. Der Zwischenstand bleibt erhalten.`;}
function score(b){return b.critical*3+Math.abs(b.feeds-3)*20+(100-b.moodSum/Math.max(1,b.samples))*2+Math.max(0,3-b.visits)*12;}function cleanBot(b){const{marker,route,...clean}=b;return{...clean,averageMood:Math.round(b.moodSum/Math.max(1,b.samples)),balanceScore:Math.round(score(b))};}
function finish(){pause();const best=[...bots].sort((a,b)=>score(a)-score(b))[0],report={createdAt:new Date().toISOString(),minutes:minute,pointCount:points.length,bots:bots.map(cleanBot),events};localStorage.setItem("ravenDaySimulationReport",JSON.stringify(report));document.getElementById("summary").textContent=`24 Stunden beendet: ${points.length} gemeinsame Punkte geprüft. ${best.name} (${best.label}) ist aktuell am ausgeglichensten.`;showRecommendation(cleanBot(best),false);render();}
function showRecommendation(best,saved){document.getElementById("recommendation").innerHTML=`<b>${saved?"Gespeichertes Ergebnis":"Erste Empfehlung"}: ${best.name} · ${best.label}</b><br>Hunger ${best.hungerHour}/h · Energie ${best.energyHour}/h · Bewegung ${best.moveCost}/km · Cooldown ${best.cooldown} Min. · ${best.visits} Radiuskontakte · Score ${best.balanceScore}.`;}
function render(){document.getElementById("clock").textContent=`Tag 1 · ${timeText()}`;const best=minute>=1440?[...bots].sort((a,b)=>score(a)-score(b))[0]:null;document.getElementById("botGrid").innerHTML=bots.map(b=>{const vm=Math.max(0,Math.round(Math.min(b.mood,(b.hunger+b.energy)/2+15)));return`<article class="bot ${best===b?"best":""}"><h3><span>${b.id+1}. ${b.name} · ${b.label}</span><small>${b.hungerHour}/${b.energyHour}/${b.moveCost}</small></h3><div class="stats"><b>🍖 ${Math.round(b.hunger)}</b><b>⚡ ${Math.round(b.energy)}</b><b>💜 ${vm}</b><b>🎒 ${b.items}</b></div><div class="bars"><div class="bar"><span>Hunger</span><i style="width:${b.hunger}%"></i><em>${Math.round(b.hunger)}</em></div><div class="bar"><span>Energie</span><i style="width:${b.energy}%"></i><em>${Math.round(b.energy)}</em></div></div><footer>${b.distance.toFixed(1)} km Straße · ${b.visits} Radiuskontakte · ${Object.keys(b.found).length} entdeckt · ${b.feeds}× gefüttert · ${b.plays}× gespielt · ${b.critical} kritische Min.</footer></article>`;}).join("");document.getElementById("eventLog").innerHTML=events.length?events.slice(-120).reverse().join("<br>"):"Noch keine Ereignisse.";}
function download(){const raw=localStorage.getItem("ravenDaySimulationReport");if(!raw)return alert("Erst eine Simulation abschließen.");const data=JSON.parse(raw),lines=["RAVEN 24-STUNDEN-STRASSENSIMULATION",data.createdAt,`Gemeinsame Punkte: ${data.pointCount}`,""];data.bots.sort((a,b)=>a.balanceScore-b.balanceScore).forEach(b=>lines.push(`${b.name}/${b.label}: Score ${b.balanceScore}, Hunger ${Math.round(b.hunger)}, Energie ${Math.round(b.energy)}, Stimmung Ø${b.averageMood}, ${b.distance.toFixed(1)} km Straße, ${b.visits} Radiuskontakte, ${Object.keys(b.found).length} entdeckt, ${b.critical} kritische Minuten`));lines.push("","EREIGNISSE",...data.events);const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([lines.join("\n")],{type:"text/plain;charset=utf-8"}));a.download="raven-24h-strassensimulation.txt";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function restoreSavedReport(){try{const data=JSON.parse(localStorage.getItem("ravenDaySimulationReport")||"null");if(!data?.bots?.length)return;const best=[...data.bots].sort((a,b)=>a.balanceScore-b.balanceScore)[0];document.getElementById("summary").textContent=`Gespeicherter Straßenbericht vom ${new Date(data.createdAt).toLocaleString("de-DE")} · ${data.pointCount||0} gemeinsame Punkte.`;showRecommendation(best,true);document.getElementById("eventLog").innerHTML=(data.events||[]).slice(-120).reverse().join("<br>")||"Keine Ereignisse.";}catch{}}
document.getElementById("startButton").onclick=start;document.getElementById("pauseButton").onclick=pause;document.getElementById("resetButton").onclick=resetSimulation;document.getElementById("downloadButton").onclick=download;initMap();loadSharedWorld().catch(error=>{document.getElementById("summary").textContent=`Fehler beim Laden der gemeinsamen Raven-Welt: ${error.message}`;});

